/* Automatically generated by version.sh - do not modify! */
#ifndef LIBRINGBUFFER_VERSION_H
#define LIBRINGBUFFER_VERSION_H

#define libringbuffer_version 0.1.0
#define libringbuffer_buildid 

#endif

